<a href="https://colab.research.google.com/github/ShivamVerma14/Data-Mining/blob/main/Practical_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Q3. Load the data from wine dataset. Check whether all attributes are standardized or not (mean is 0 and standard deviation is 1). If not, standardize the attributes. Do the same with Iris dataset.

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_wine, load_iris

### Wine Dataset

In [ ]:
data = load_wine()

X = data.data

**Mean and standard deviation along the columns.**

In [ ]:
X.mean(axis=0)

array([1.30006180e+01, 2.33634831e+00, 2.36651685e+00, 1.94949438e+01,
       9.97415730e+01, 2.29511236e+00, 2.02926966e+00, 3.61853933e-01,
       1.59089888e+00, 5.05808988e+00, 9.57449438e-01, 2.61168539e+00,
       7.46893258e+02])

In [ ]:
X.std(axis=0)

array([8.09542915e-01, 1.11400363e+00, 2.73572294e-01, 3.33016976e+00,
       1.42423077e+01, 6.24090564e-01, 9.96048950e-01, 1.24103260e-01,
       5.70748849e-01, 2.31176466e+00, 2.27928607e-01, 7.07993265e-01,
       3.14021657e+02])

**Standardizing the dataset.**

In [ ]:
sc = StandardScaler()
X = sc.fit_transform(X)

In [ ]:
X.mean(axis=0)

array([ 7.84141790e-15,  2.44498554e-16, -4.05917497e-15, -7.11041712e-17,
       -2.49488320e-17, -1.95536471e-16,  9.44313292e-16, -4.17892936e-16,
       -1.54059038e-15, -4.12903170e-16,  1.39838203e-15,  2.12688793e-15,
       -6.98567296e-17])

In [ ]:
X.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Iris Dataset

In [ ]:
data = load_iris()

X = data.data

**Mean and standard deviation along the columns.**

In [ ]:
X.mean(axis=0)

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [ ]:
X.std(axis=0)

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

**Standardizing the dataset.**

In [ ]:
sc = StandardScaler()
X = sc.fit_transform(X)

In [ ]:
X.mean(axis=0)

array([-1.69031455e-15, -1.84297022e-15, -1.69864123e-15, -1.40924309e-15])

In [ ]:
X.std(axis=0)

array([1., 1., 1., 1.])